script: true
notifications:
  email: false
env:
  - FOO=1
  - FOO=2
conditions: v1
jobs:
  include:
    - stage: Yo!
      script: echo stages
      # this is a parse error on v1, and should not produce a stage anymore
      if: branch NOT (sf-stages-passing)
