language: ruby
dist: trusty
install: echo "true"
script: 
- 'echo wat: $WAT'
- bitcoind
env:
  global:
    secure: LJcFJvvRznvsEChbvz3cpMj2KAa0h99q1/ZxmpZvRNXM+2KiD8SmDINTQl+5fBXnJOIyKUH5M0bZhBG86pK61Bj+gTtX62pHDBakFrnRfP/VYPlmdFkU146UiRGVfdYg8lyI/qsoIVZz1y4pmdUfvJbusPa/EdvveB409xDanObh9ahMdrV9FQfoE5/Qbp8hTvfKf55sEaQeWrdCuwfn6TbKSV04bd0+fh4+JIyYMpsgeQ4oy7PCPS0366FnMBVqkANeHuipNP68RreKrCJcTy4lbm2j8JfiQVlDP9nZKKHTyiEbLhs5BF3bio3YeG0OPIRpBh7B4DgTOyZ1CIAE6vfeuxBMrwt2X26ObpOsxTyTUoJwGabQJQd6Yg3cbbt18YZkFikcLwLETRdFoP4oO+knUUtgFrUZa/9XFj/skuwPNnHYS2BfNJqbnB5Q4fCNuME9jNd+XSNaLyLucqMtOI/qpX9iIZ2Yg9EXU+0nZzCG2ZOMzya852/g/AZGLa9j3bOtYoZ8mf/rGiXD2Exrx1cYucRCBEbD8cjSR7/CI4G8Jgokw6UiuE2siix5xPYcgn/blpEDz9qNInIHbDRyA+LO839y/1kB8/KF9CRa0mXxFr/nEPCoFpL+VMKPLdGgWBPQOC6Z31XWUoF2O/JVOzGy2mAdGILrrh5q5B0zuOw=
