# version: '= 0'
conditions: v1

language: generic
install: skip

jobs:
  include:
    - script: echo unconditional
    - script: echo $FOO
      if: env(FOO) = branch
      env: FOO=master
    - script: echo $FOO
      if: env(FOO) = branch
      env: FOO=other
