# version: '= 0'

language: generic
install: skip

env:
  global:
    - FOO=master
    
jobs:
  include:
    - name: one
      script: echo one
      if: env(FOO) = branch
    - name: two
      script: echo two
      if: env(FOO) != branch
